# Generated by Django 4.2 on 2023-05-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='id',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(max_length=11),
        ),
    ]
